ERPNEXT_COMPANY=MickMake
ERPNEXT_CUSTOMER_GROUP=All Customer Groups
ERPNEXT_TERRITORY=All Territories
ERPNEXT_ITEM_GROUP=All Item Groups
ERPNEXT_COUNTRY=Australia
ERPNEXT_CURRENCY=AUD
ERPNEXT_INCOME_ACCOUNT=41040 - Service Income - MM
ERPNEXT_RECEIVABLE_ACCOUNT=12010 - Trade Debtors - MM
ERPNEXT_BANK_ACCOUNT=11510 - Every Day Bank Account - MM
ERPNEXT_MODE_OF_PAYMENT=Bank Transfer
ERPNEXT_UOM=Nos
ERPNEXT_SELLING_PRICE_LIST=Standard Selling
ERPNEXT_TAX_TEMPLATE=AU Sales - GST - MM

