name: GoBunningsNinja

on:
  pull_request:
    paths:
      - 'apps/GoBunningsNinja/**'
      - '.github/workflows/gobunningsninja.yml'

  push:
    branches:
      - main
    paths:
      - 'apps/GoBunningsNinja/**'

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: apps/GoBunningsNinja

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...
